services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Framework\SystemRequirements\SystemSecurityCheckerInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\SystemRequirements\SystemSecurityChecker

  OxidEsales\EshopCommunity\Internal\Framework\SystemRequirements\Bridge\SystemSecurityCheckerBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\SystemRequirements\Bridge\SystemSecurityCheckerBridge
    public: true
